---
# Defaults for the mongodb role. These are the lowest priority variables
# and can easily be overridden in group_vars, host_vars, or command line.
# Largely these should be sensible defaults and show not require changing.

db_name: picoCTF
db_data_path: "/data"

# MongoDB User Variables (used in configure_auth.yml task)
# Passwords should be stored outside version control or in an
# ansible-vault protected file.
initial_admin_name: picoAdmin
initial_admin_password: "{{ picoAdmin_db_password }}"

# Add additional users an environment specific group_vars file
mongodb_users: "{{ env_db_users }}"

###
# MongoDB Configuration Variables (used in configure_mongo.yml task)
###
mongodb_user: mongodb
mongodb_daemon_name: mongod

mongodb_apt_keyserver: keyserver.ubuntu.com
mongodb_apt_key_id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
mongodb_repo: 'deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse'

mongodb_conf_auth: true                                               # Run with security
mongodb_conf_bind_ip: "0.0.0.0"                                       # IP addresses to listen on (Static)
mongodb_conf_port: 27017                                              # Port number
mongodb_conf_journal: true                                            # Enable journaling
mongodb_conf_logappend: true                                          # Append instead of over-writing
mongodb_conf_logpath: /var/log/mongodb/{{ mongodb_daemon_name }}.log  # Log to file (not stdout)
mongodb_conf_dbpath: "{{ db_data_path }}"                             # Directory for datafiles (Static)

###
# AWS specific mount points (defined in Terraform - static)
##
on_aws: False
db_data_device: "/dev/xvdf"
db_data_device_fstype: "ext4"
db_data_mount_opts: "defaults,auto,noatime,noexec 0 0"

