---
# Playbook that sets the server's hostname

- name: Set hostname
  hostname:
    name: "{{ hostname }}"

- name: Update /etc/hosts with hostname
  lineinfile:
    dest: '/etc/hosts'
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1  {{ hostname }}"
