---
# Playbook to handle convenience preconfigurations so an admin is not
# required to set things up in the web ui by hand.


- name: Autoload Shell Server into web interface
  script: >
    add_shell_server.py
    {{ shell_name }}
    {{ shell_ip }}
    {{ shell_user }}
    {{ shell_pass }}
    {{ shell_port }}
    {{ shell_proto }}
  environment:
    APP_SETTINGS_FILE: "{{ web_config_dir }}/deploy_settings.py"
    PATH: "{{ virtualenv_dir }}/bin/"
  args:
    executable: "{{ virtualenv_dir }}/bin/python"
  when: auto_add_shell
  no_log: True

- name: Autoload Problems into web interface
  script: load_problems.py {{ shell_name }}
  environment:
    APP_SETTINGS_FILE: "{{ web_config_dir }}/deploy_settings.py"
    PATH: "{{ virtualenv_dir }}/bin/"
  args:
    executable: "{{ virtualenv_dir }}/bin/python"
  when: auto_load_problems

- name: Auto Start competition
  script: start_competition.py
  environment:
    APP_SETTINGS_FILE: "{{ web_config_dir }}/deploy_settings.py"
    PATH: "{{ virtualenv_dir }}/bin/"
  args:
    executable: "{{ virtualenv_dir }}/bin/python"
  when: auto_start_competition

